replicaCount: 1

image:
  repository: atlassian/jira-software
  tag: 8.15.0-ubuntu-jdk11
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  jvmMinimumMemory: "1024m"
  jvmMaximumMemory: "2048m"

persistence:
  size: 10Gi

tailscale:
  tsKubeSecret: "tailscale-auth"