apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "jira.fullname" . }}-data-pvc
  labels:
    {{- include "jira.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}