apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: {{ include "jira.fullname" . }}-tailscale-secret-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing Secret
  # objects is "secrets"
  resources: ["secrets"]
  resourceNames: [{{.Values.tailscale.tsKubeSecret}}]
  verbs: ["get", "watch", "list", "update"]