apiVersion: v1
kind: Service
metadata:
  name: {{ include "jira.fullname" . }}-software-service
  labels:
    {{- include "jira.labels" . | nindent 4 }}
spec:
  type: NodePort  # or LoadBalancer if you're on a cloud provider that supports it
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}  # only needed for NodePort type
  selector:
    {{- include "jira.selectorLabels" . | nindent 4 }}